### ISSUE TITLE
atlas_code

### ISSUE THREAD

**Issue by lpofredc** [dthonon/ExportVN#10]
Dear Daniel, 
There is no **atlas_code** column in **observations** table.
Thanks,

**Comment by dthonon** [comment]
Corrected in v0.6.1

**Comment by dthonon** [comment]
Fred;
J'ai corrigé, ainsi que l'absence de behaviours. Après un git pull, il faut
refaire ./evn.sh store pour vérifier.
Daniel

2016-10-17 17:29 GMT+02:00 lpofredc notifications@github.com:

**Comment by lpofredc** [comment]
Ca fonctionne, merci!

Frédéric CLOITRE
LPO Ardèche
Vos observations sur : www.faune-ardeche.org
